### ISSUE TITLE
API and online check show different results for 371535

### ISSUE THREAD

**Issue by colmcraddock** [binlist/binlist-data#146]
When you use BIN 371535 online on site it shows as AMEX CREDIT. However using API @ "https://lookup.binlist.net/371535" the result is a VISA debit. 
Thanks,
Colm

**Comment by kladskull** [comment]
May 9? Abandoned project? I get the same... in July.... 

curl https://lookup.binlist.net/370754
{"scheme":"VISA","number":{"length":19,"prefix":"370754"},"type":"DEBIT","brand":"Visa Plus","prepaid":false,"bank":{},"country":{"alpha2":"US","name":"United States","numeric":"840","latitude":38,"longitude":-97}}

**Comment by tjconcept** [comment]
Hi @colmcraddock and @mikecurry74 

Please see the website regarding the `Accept-Version` header. If you query the service without you will hit an older version of the API with stale data.
