### ISSUE TITLE
53487000 is a Bank of America Business Debit Card (MC)

### ISSUE THREAD

**Issue by wwwmaster1** [binlist/binlist-data#148]
I've gone through 3 cards now thinking the IIN was messed up because a payment provider would not accept the card as a debit card. It turns out the record does not exist on the list. I'd be happy to send you a few photos to confirm.

**Comment by tjconcept** [comment]
Thanks. Please submit as many answers for the following form to binlist@src.agency: https://gist.github.com/tjconcept/a839e6715a7e71c11c0f508c0cc6323b to correct the IIN.
