### ISSUE TITLE
379186 is VISA via api

### ISSUE THREAD

**Issue by senglun** [binlist/binlist-data#151]
tested the above account via api it returns VISA

{"scheme":"VISA","number":{"length":19,"prefix":"379186"},"type":"DEBIT","brand":"Visa Plus","prepaid":false,"bank":{},"country":{"alpha2":"US","name":"United States","numeric":"840","latitude":38,"longitude":-97}}

but when search via the web it returns as amex

**Comment by tjconcept** [comment]
Hi @senglun,

It's most likely because you forgot the `Accept-Version: 3` header for the API.

**Comment by senglun** [comment]
ok that worked
