### ISSUE TITLE
Error response always ZERO

### ISSUE THREAD

**Issue by idemax** [binlist/binlist-data#153]
Hi, 

I'm trying to request the service via `https://lookup.binlist.net/<number>` but even if the HTTP response is coming 4** when is wrong to exploding the time limit, in the browser is always coming ZERO. For example, I'm trying call it via JQuery AJAX (2.1.0) but the ZERO callback is always called no matter what.

Example:
```
$.ajax({
    url: "https://lookup.binlist.net/" + cardNumber,
    dataType: 'json',
    cache: false,
    headers: {
        'Accept-Version': '3'
    },
    statusCode: {
        0: function () {
            console.log("ZERO!");
        },
        200: function () {
            console.log("200");
        },
        400: function () {
            console.log("400");
        },
        404: function () {
            console.log("404");
        },
        429: function () {
            console.log("429");
        }
    },
    error: function (data, status, error) {
        console.log(data); // object
        console.log(data.status); // 0 (zero)
        console.log(status); // error
        console.log(error); // EMPTY
    }
});
```

Is there something missing?

**Comment by tjconcept** [comment]
Hi @marcelolfilho 

I am afraid I do not know how `$.ajax` works, or can offer any support on that.

If you believe the server is responding incorrectly to a request, please submit a cURL command for reproducing the error and I will happily look into into.
