### ISSUE TITLE
This Bank assigned to BIN's 437727  is incorrect

### ISSUE THREAD

**Issue by jefflgeren** [binlist/binlist-data#155]
The correct information is
BOKF, N.A.
This is a VIA debit card assigned to Postel Family CU

I notice many BIN's as not correct how do you update this information
BIN 437727

•	SCHEME / NETWORK
Visa
•	BRAND
Traditional
•	CARD NUMBER
O	LENGTH
16
O	LUHN
1.	Yes
2.	No
•	TYPE
1.	Debit
•	COUNTRY
USA
•	BANK
BOKF

**Comment by tjconcept** [comment]
Please submit as many answers for the following form to binlist@src.agency: https://gist.github.com/tjconcept/a839e6715a7e71c11c0f508c0cc6323b to correct or add new IINs.
