### ISSUE TITLE
Data from website and api is different

### ISSUE THREAD

**Issue by rizky-akbar** [binlist/binlist-data#156]
![image](https://user-images.githubusercontent.com/6258895/30498551-61860324-9a81-11e7-96be-cd821ea200d3.png)
![image](https://user-images.githubusercontent.com/6258895/30498613-91a7185e-9a81-11e7-8954-e616d95e3040.png)

**Comment by tjconcept** [comment]
You are missing the `Accept-Version` header.
Same as https://github.com/binlist/data/issues/154.
