### ISSUE TITLE
37335959

### ISSUE THREAD

**Issue by paulb057** [binlist/binlist-data#169]
This is an Amex however https://lookup.binlist.net/37335959 says it is a VISADEBIT. However when you use https://binlist.net/ it show you the correct information

**Comment by PietroBelloPpz** [comment]
@paulb057 I had the same issue, then i found https://github.com/binlist/data/issues/146 : when I specify the hader "Accept-Version: 3" as stated in the website, I get correct values.

**Comment by tjconcept** [comment]
Thanks @PietroBelloPpz
