### ISSUE TITLE
South Korea card issuer bin

### ISSUE THREAD

**Issue by U-siro** [binlist/binlist-data#172]
Here is BIN list of south korea cards. It includes all card issuer.
https://www.kicc.co.kr/kr/support/pds/van/pds_van_view.jsp?s_menu=4 and download xls.

**Comment by BasixKOR** [comment]
I will check it out and open a pull request.

**Comment by tjconcept** [comment]
> Here is BIN list of south korea cards. It includes all card issuer.

Probably not.

Please submit answers for the following form to binlist@src.agency: https://gist.github.com/tjconcept/a839e6715a7e71c11c0f508c0cc6323b to correct or add new IINs.
Only pull requests correcting single entries for which you hold a card (as proof) will be accepted.

**Comment by BasixKOR** [comment]
@tjconcept That site is owned by real VAN company, and their BIN table have public confidence in Korea. I'm moving their BIN infomation to BasixKOR/binlist-data, so please check it out.

**Comment by tjconcept** [comment]
> VAN company

What's that?

**Comment by BasixKOR** [comment]
@tjconcept VAN company is card payment terminal company. They provide card payment service to card affiliated stores.
