### ISSUE TITLE
MasterCard - Expansion to 2-series Bank Identification Numbers (BINs)

### ISSUE THREAD

**Issue by frekele** [binlist/binlist-data#178]
Expansion to 2-series Bank Identification Numbers (BINs)

Bank Identification Numbers (BINs), which are the first six-digits of the account number, are fundamental to payments. They identify the issuing institution for the account and ensure that each transaction is routed correctly.
Mastercard® has received an additional range of 2-series numbers (range 222100-272099) to add to the 5-series (range 510000-559999) that we currently provide. The 2-series BINs operate in the same way as the 5-series and we have made changes to our systems to accommodate the new numbers. Readiness for the 2-series across our issuers, merchants and other partners is tracking on target dates listed below. Mastercard customer financial institutions can expect to be issued 2-series BINs starting in 2017.

![mc-world-credit-card_2bin-contactless-lmc-360x360](https://user-images.githubusercontent.com/2288215/35451961-180ef64a-02ac-11e8-8a3a-afe0f7b87f2d.jpg)

REF: https://www.mastercard.us/en-us/issuers/get-support/2-series-bin-expansion.html

**Comment by tjconcept** [comment]
Please submit answers for the following form to binlist@src.agency: https://gist.github.com/tjconcept/a839e6715a7e71c11c0f508c0cc6323b to correct or add new IINs.
