### ISSUE TITLE
Amex Lookup via API Returns Visa Debit (UI Returns Amex Correctly)

### ISSUE THREAD

**Issue by jliversidge** [binlist/binlist-data#182]
When validating an Amex card number, the API returns Visa Debit:
E.g: 
https://lookup.binlist.net/371449
{
"scheme": "VISA",
"number": {
"length": 19,
"prefix": "371449"
},
"type": "DEBIT",
"brand": "Visa Plus",
"prepaid": false,
"bank": {},
"country": {
"alpha2": "US",
"name": "United States",
/********************/

The UI at https://binlist.net/ correctly identifies Amex:
SCHEME / NETWORK: Amex
BRAND: american express

**Comment by tjconcept** [comment]
Same as #146
