### ISSUE TITLE
Bnext Spain

### ISSUE THREAD

**Issue by AlfonsoSBLA** [binlist/binlist-data#185]
Add the BIN for Bnext (Pecunia Cards) 42088409

![image](https://user-images.githubusercontent.com/37416851/37482416-68c18582-2884-11e8-9604-4a2c0749c78f.png)

Other repositories already have it

**Comment by AlfonsoSBLA** [comment]
# Primary account number (card number)
Range start: 420884
Range end:
Leave the "Range end" empty if identical to "Range start"
Total length: 6
LUHN: YES

# Card details
Network: VISA
Brand: Prepaid
Country: 724
Type: Debit
Prepaid: Yes
E-commerce: Yes
ATM: Yes
OTC: No

# Organizations

**Card manager**
Name: Bnext
Address: Avenida de San Luis, nº 148, 28033 - Madrid (España)
Country: Spain
Phone: +34-668693339
Website: https://bnext.es/
Logo: https://bnext.es/wp-content/uploads/2018/02/logo-1.png
Support: Yes
Branded: Yes
Issuer: No

**Card Issuer**
Name: Pecunia Cards E.D.E. S.L.U.
Address: Calle Guzman el Bueno, 133, Edificio America, 28003 - Madrid (España)
Country: Spain
Phone: +34-668693339
Website: https://bnext.es/
Logo: https://www.pecunpay.es/wp-content/themes/html5blank-stable/img/menu_logo.png
Support: Yes
Branded: No
Issuer: Yes

# Other
Additional information:
Role of submitter: Card Owner
Source: We are the ones providing the card to our clients.

**Comment by tjconcept** [comment]
Contributed by other source.
