### ISSUE TITLE
VISA from Jyske Bank (DK)

### ISSUE THREAD

**Issue by MJoergen** [binlist/binlist-data#195]
The VISA card from Jyske Bank (4571 5010) is incorrectly reported as a Debet card. According to the bank, it is a Credit card.

**Comment by tjconcept** [comment]
Is it a Dankort?

**Comment by MJoergen** [comment]
Yes, it is a VISA/Dankort.
My bank is giving me contradictory information.

man. 2. jul. 2018 15.04 skrev Thomas Jensen <notifications@github.com>:

**Comment by tjconcept** [comment]
That's the reason then. The VISA part is a debitt on all Dankort.
