### ISSUE TITLE
Incorrect type for BIN

### ISSUE THREAD

**Issue by g4s8** [binlist/binlist-data#207]
https://binlist.net/ claims that BIN `521324` is a credit card, but it's actually a debit card:
![scrot-2019-03-15-13:48:35](https://user-images.githubusercontent.com/1524988/54426625-68438f00-4729-11e9-92e2-930100b04361.png)

**Comment by stavcode412** [comment]
@g4s8 - was this issue resolved? We are having the same issue and wonder how did you corrected it.

**Comment by h8nor** [comment]
> ![изображение](https://user-images.githubusercontent.com/6163937/97364939-e3819680-18b5-11eb-8396-a385ce16d6b0.png)


Please could you update it with the correct information:

type: debit
brand: classic

Thank you!

**Comment by cocoo-star** [comment]
Any fresh bins for azure portal ?

**Comment by tjconcept** [comment]
According to Mastercard, it is a credit card.

**Comment by h8nor** [comment]
@tjconcept Please write why you ignored the correct information? Need a confirmation photo of card?

**Comment by tjconcept** [comment]
The data from Mastercard is authoritative. It's what's used for fee calculations and routing in the card network, thus regardless of what your card says, it's treated as a credit.

If you can submit a picture of the card with sensitive details masked (1234 45** **** 1234, expiry, CVC, and name) I'll see if I can ask someone at Mastercard.

**Comment by h8nor** [comment]
@tjconcept Your desire contradicts the bank's recommendation on non-disclosure of personal data. There is no overdraft on the card. I will take into account that the service contains errors in the Mastercard.

**Comment by tjconcept** [comment]
> non-disclosure of personal data

Please redact all personal data.

**Comment by h8nor** [comment]
@tjconcept Do you need data or the fact of having a card? If the first, then I can make a closed link on video to an invalid card, so that you may be sure of the data's error.

**Comment by g4s8** [comment]
@tjconcept please check this photo: the card number starts with `5213 24` and it's a debit card, not credit. ![photo_2020-11-18_17-49-35](https://user-images.githubusercontent.com/1524988/99545541-8b2a4a00-29c6-11eb-99fb-d77a2b9512c0.jpg)

**Comment by tjconcept** [comment]
Thank you, I'll bring that up with Mastercard.

**Comment by h8nor** [comment]
Apparently something went wrong. Now all maps of Mastercard of the Russian Federation (#227 and not only) [are displayed](//binlist.net) as "**Credit**".
