### ISSUE TITLE
51482100 wrong website

### ISSUE THREAD

**Issue by Cu-ccuHannah** [binlist/binlist-data#210]
Hi,

I'd posted previously regarding a bin associated with my company website, and we do not own that BIN. We've been receiving subpoenas for people who are in no way associated with us. 
I asked for the bin to be reset and the website blanked out, I got some responses, and then the whole post was deleted. 

5148 21
The website links to mycucommunity.com
Which has rebranded to multiplicu.com. I can provide the bins we own, and none of the existing bins we own are currently listed on binlist.net [unless the guy who deleted my post put them up there when I gave them to him, I haven't checked].

**Comment by tjconcept** [comment]
It seems this has been fixed?
