### ISSUE TITLE
522319 BIN returns wrong information

### ISSUE THREAD

**Issue by ntimo** [binlist/binlist-data#216]
Hello,
the BIN search for 522319 returns wrong and outdated info. The BIN has been assigned to bunq (bunq.com). Could you maybe update the database? :)

Best wishes,
Timo

**Comment by tjconcept** [comment]
Hi Timo,

I see a small subset of 522319 being assigned to another member with Netherlands as the country, however, Mastercard still advertises the entire 522319* range to another member.

Can you provide proof (contact@binlist.net) that this entire prefix is reassigned?

**Comment by salixh5** [comment]
Hey, I got a new card from bunq as a German customer with 5223 1903. All my other cards from bunq are registered as German, only this card shows Russia, which is probably not correct.

I'm just a customer so I don't know how to prove anything, but it seems that bunq is using the 8th digit for the customer's country of residence (2 being Netherlands, 3 Germany, 4 Austria, ... and so on?)

Edit: While the 52231903 card is credit, my other bunq card is a debit Mastercard and has the BIN 53746503. Maybe that helps. With their debit cards there seems to be the same thing going on on 8th digit. 🇳🇱🇩🇪
