### ISSUE TITLE
Is currency directly related with the card or the currency used in that country

### ISSUE THREAD

**Issue by andreas22** [binlist/binlist-data#220]
I appologize for my ignorance but I would like to ask you which currency is returned inside the response `Card` or `Country` currency?

For example I might have a Card issued in Japan where local currency is JPY and card is in USD. Which currency do I get inside the response?

**Comment by binlistnet** [comment]
Hi Andreas,

You get the currency associated with the country, not necessarily the card.
I'm afraid it's impossible to query the actual currency of a card which is
why the country-based currency is often the one considered the most likely.

**Comment by andreas22** [comment]
I see, finding a way though to know what currency a card is will save also a lot of currency convertions when making payments. Thanks
