### ISSUE TITLE
BIN 5480 12 is a debit card

### ISSUE THREAD

**Issue by carolrivera2** [binlist/binlist-data#227]
Hi. My business debit card from Capital One bank has a number that begins with 5480 12, and although the card has "Debit" printed on it and the bank classifies it as a debit card, it's classified as a credit card on your site. Can this be updated to Debit? Thank you.

(I haven't been able to use the card for GooglePay because Google also says that it's a credit card. I wonder if they could be getting their information from your site? I haven't been able to reach any resolution with Google or with the bank, so I'm hoping that your update, and any advice you could give, may help. Thanks again.)

**Comment by samymassoud** [comment]
It looks like it is a debit card

https://bintable.com/bin/548012

**Comment by carolrivera2** [comment]
Hi. Thanks for the reply. Yes, it does look like a debit card at the link
you sent, and it has "Debit" printed on it and it was issued by the bank,
Capital One, as a debit card.

But why does it come up as Credit for the card type at https://binlist.net?
How can I have the card type changed there?

Thank you,
Carol Rivera

**Comment by tjconcept** [comment]
I'm afraid, from Mastercard themselves, both a debit and a credit card exist with that prefix. It might require the full card number or use (ATM, ecommerce, region, etc.) to tell which one of the ranges a card is.

**Comment by carolrivera2** [comment]
Hello. When I put the full credit card number in at https://binlist.net the
card shows up as a credit card, but it is actually a debit card. I can
provide a few more numbers if needed? Please let me know what information I
would need to provide to have the record adjusted. Thank you.

Carol Rivera

**Comment by tjconcept** [comment]
Looking more into this, the two Mastercard ranges are not differentiated on the card number alone.

There is a Cirrus (debit card) and a Commercial/Business (credit card). The credit card has a higher priority.

Could you submit a picture of the front of your card, masking the card number and other sensitive details?

**Comment by carolrivera2** [comment]
Yes, here's a picture of the card with just the first few numbers and my
first name showing. Does this work for being able to resolve the issue?
Thanks!

Carol

**Comment by tjconcept** [comment]
I'm afraid I don't see any picture.

**Comment by carolrivera2** [comment]
Hi. I attached it and see it attached to my previous email. You don't see
an attachment that can be downloaded? Would Gmail remove it? I have now
pasted it below into the email. Do you see it now?

Thanks,
Carol

[image: image.png]

**Comment by tjconcept** [comment]
I don't think GitHub supports sending in attachments.

**Comment by carolrivera2** [comment]
Is there another way I can send you the image?

Carol

**Comment by tjconcept** [comment]
Yes, just go to GitHub and upload it to this issue.

**Comment by carolrivera2** [comment]
Okay, uploading it here. 
![IMG_0415 rev](https://user-images.githubusercontent.com/58344049/99193858-a89eb000-2749-11eb-87b4-c6ca60997306.jpg)

Carol
