### ISSUE TITLE
BIN 549949 returns wrong information

### ISSUE THREAD

**Issue by luis92arma** [binlist/binlist-data#232]
Título: BIN 549949 returns wrong information

Hello,

When querying for this BIN the service responds with:

SCHEME / NETWORK: Mastercard
BRAND: Gold

CARD NUMBER
LENGTH: 
LUHN: 

TYPE: Credit
PREPAID: 
COUNTRY: 🇷🇺 Russian Federation
BANK: MOSCOW MUNICIPAL BANK-BANK OF MOSCOW

The correct information is:

SCHEME / NETWORK: Mastercard
BRAND: Gold

CARD NUMBER
LENGTH: 
LUHN: 

TYPE: Credit
PREPAID: No
COUNTRY:   🇲🇽 Mexico  
BANK: BANAMEX

Would you please help me to correct this information?

Thanks!

**Comment by tjconcept** [comment]
Fixed.
