### ISSUE TITLE
BIN 448008 misconfigured

### ISSUE THREAD

**Issue by ALCSnap** [binlist/binlist-data#233]
This BIN is configured incorrectly, and returns the incorrect information:

![Screenshot 2020-01-27 at 12 40 14](https://user-images.githubusercontent.com/60344467/73168375-5cbf4380-4102-11ea-8b07-b7ee467d247b.png)

Please could you update it with the correct information:

Bank: FIRSTRAND BANK, LTD.
Country: South Africa

Thank you!

**Comment by tjconcept** [comment]
Fixed.
