### ISSUE TITLE
BINs - Corrections

### ISSUE THREAD

**Issue by jakubroj** [binlist/binlist-data#255]
I can't seem to create a pull request, but please see corrections that I've noticed. 
Your work is much appreciated. Thank you and Happy New Year!

557511 - is mBank (formerly BRE BANK POLSKA)
510621 - is YooMoney Russia (formerly Yandex Money RU) - unsure whether CSCU is used for these cards
476367 - is TSB UK
424671 - is ING Bank Slaski (Poland)
405671 - is mBank (formerly BRE BANK POLSKA)
475142 - is Nationwide Building Society
454313 - is Nationwide Building Society
537434 - is TransferWise
535584 - is N26 Deutschland
376683 - is American Express (AMEX) - United Kingdom, not Mexico.

**Comment by cocoo-star** [comment]
tnx😙
